# Generated by Django 2.0.7 on 2019-04-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_user', '0005_goodsbrowser_browser_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='uemail',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uname',
            field=models.CharField(max_length=20, unique=True, verbose_name='用户名'),
        ),
    ]
