# Generated by Django 2.0.7 on 2018-12-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetailinfo',
            options={'verbose_name': '订单详情', 'verbose_name_plural': '订单详情'},
        ),
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='count',
            field=models.IntegerField(verbose_name='商品数'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_goods.GoodsInfo', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_order.OrderInfo', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='orderdetailinfo',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='oIsPay',
            field=models.BooleanField(default=False, verbose_name='是否支付'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='oaddress',
            field=models.CharField(max_length=150, verbose_name='订单地址'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='odate',
            field=models.DateTimeField(auto_now=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='oid',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='大订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='ototal',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_user.UserInfo', verbose_name='订单用户'),
        ),
    ]
